#!/bin/bash

cleanup() {
  kill $pid1 2>/dev/null
}

if [ -z "$POLL" ]; then
  condor_diagnostics -w 5 \
  --prometheus ./metrics/metrics.prom \
  --silent & pid1=$!
  trap cleanup EXIT INT TERM
  sudo docker-compose up --build &
  wait $!
else
  sudo docker-compose up --build
fi